import crypto from "crypto";

// The secret key used to sign the OTP hash. 
// IN PRODUCTION: This MUST be a strong, random string stored in your .env file!
const OTP_SECRET = process.env.OTP_SECRET || "fallback-secret-key-change-me-in-production";

/**
 * Generates a stateless hash for an OTP.
 * @param email The user's email address
 * @param otp The 6-digit OTP code
 * @param expiresInMinutes How long the OTP should be valid for (default: 5)
 * @returns A string combining the cryptographic hash and the expiration timestamp, formatted as "hash.expiresAt"
 */
export function generateOtpHash(email: string, otp: string, expiresInMinutes: number = 5): string {
  // 1. Calculate when this OTP should expire
  const expiresAt = Date.now() + expiresInMinutes * 60 * 1000;
  
  // 2. Create the data string that we want to sign
  const data = `${email.toLowerCase()}:${otp}:${expiresAt}`;
  
  // 3. Create a cryptographic HMAC SHA-256 hash
  const hash = crypto.createHmac("sha256", OTP_SECRET).update(data).digest("hex");
  
  // 4. Return the hash and the expiration time together
  return `${hash}.${expiresAt}`;
}

/**
 * Verifies if a given OTP matches the stateless hash.
 * @param email The user's email address
 * @param otp The 6-digit OTP code the user entered
 * @param hashWithExpires The "hash.expiresAt" string previously generated by generateOtpHash
 * @returns true if valid and not expired, false otherwise
 */
export function verifyOtpHash(email: string, otp: string, hashWithExpires: string): boolean {
  if (!hashWithExpires || !hashWithExpires.includes(".")) {
    return false;
  }

  const [hash, expiresAtStr] = hashWithExpires.split(".");
  const expiresAt = parseInt(expiresAtStr, 10);

  // 1. Check if the OTP is expired
  if (Date.now() > expiresAt) {
    return false;
  }

  // 2. Re-create the hash using the provided email, otp, and the extracted expiration time
  const data = `${email.toLowerCase()}:${otp}:${expiresAt}`;
  const validHash = crypto.createHmac("sha256", OTP_SECRET).update(data).digest("hex");

  // 3. Compare the newly generated hash with the hash provided by the client
  // Using timingSafeEqual prevents timing attacks, though a simple === works for basic use cases.
  return crypto.timingSafeEqual(Buffer.from(hash), Buffer.from(validHash));
}

/**
 * Generates a random 6-digit OTP string.
 */
export function generateRandomOtp(): string {
  // Generates a random number between 100000 and 999999
  return Math.floor(100000 + Math.random() * 900000).toString();
}
